// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASrqr0s_azULHR55DaFPtWE9tf93fEcPc',
    appId: '1:199883911433:web:7c52264d587b8f6dde23d8',
    messagingSenderId: '199883911433',
    projectId: 'student-personalized-app-29c77',
    authDomain: 'student-personalized-app-29c77.firebaseapp.com',
    storageBucket: 'student-personalized-app-29c77.firebasestorage.app',
    measurementId: 'G-B6WV59QWB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaztKucAxN-1jdPe3oxNXjz91_rerNfmA',
    appId: '1:199883911433:android:e9ccde1bf265e94bde23d8',
    messagingSenderId: '199883911433',
    projectId: 'student-personalized-app-29c77',
    storageBucket: 'student-personalized-app-29c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVQNHVQQiGmod95MAODICJpGNoY-eJ6x4',
    appId: '1:199883911433:ios:f18605162d520a38de23d8',
    messagingSenderId: '199883911433',
    projectId: 'student-personalized-app-29c77',
    storageBucket: 'student-personalized-app-29c77.firebasestorage.app',
    androidClientId: '199883911433-bc0j8cbpblrl81tcr9eqf8sh1aq4uiva.apps.googleusercontent.com',
    iosClientId: '199883911433-pjd5186p7f2m65vovjgsai4qrhtehnc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVQNHVQQiGmod95MAODICJpGNoY-eJ6x4',
    appId: '1:199883911433:ios:f18605162d520a38de23d8',
    messagingSenderId: '199883911433',
    projectId: 'student-personalized-app-29c77',
    storageBucket: 'student-personalized-app-29c77.firebasestorage.app',
    androidClientId: '199883911433-bc0j8cbpblrl81tcr9eqf8sh1aq4uiva.apps.googleusercontent.com',
    iosClientId: '199883911433-pjd5186p7f2m65vovjgsai4qrhtehnc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASrqr0s_azULHR55DaFPtWE9tf93fEcPc',
    appId: '1:199883911433:web:76a2a0967c761a99de23d8',
    messagingSenderId: '199883911433',
    projectId: 'student-personalized-app-29c77',
    authDomain: 'student-personalized-app-29c77.firebaseapp.com',
    storageBucket: 'student-personalized-app-29c77.firebasestorage.app',
    measurementId: 'G-DC1PG2KHNX',
  );
}
