"""updated auth route registration

Revision ID: 4c68364da00e
Revises: add_course_structure
Create Date: 2025-10-19 00:55:18.467918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c68364da00e'
down_revision = 'add_course_structure'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_path_id'), ['path_id'], unique=False)

    with op.batch_alter_table('path_modules', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_pathmodule_path'))
        batch_op.create_index(batch_op.f('ix_path_modules_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('path_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_path_modules_course_id'))
        batch_op.create_index(batch_op.f('idx_pathmodule_path'), ['path_id', 'order'], unique=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_path_id'))

    # ### end Alembic commands ###
