"""fix foreign key constraints

Revision ID: fix_foreign_key_constraints
Revises: learning_path_enhancement_v1
Create Date: 2025-11-04 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fix_foreign_key_constraints'
down_revision = "learning_path_enhancement_v1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key constraints that don't have CASCADE
    op.drop_constraint('path_modules_path_id_fkey', 'path_modules', type_='foreignkey')
    op.drop_constraint('path_modules_course_id_fkey', 'path_modules', type_='foreignkey')
    op.drop_constraint('courses_path_id_fkey', 'courses', type_='foreignkey')
    op.drop_constraint('user_progress_module_id_fkey', 'user_progress', type_='foreignkey')
    op.drop_constraint('user_progress_profile_id_fkey', 'user_progress', type_='foreignkey')
    op.drop_constraint('learning_paths_user_id_fkey', 'learning_paths', type_='foreignkey')
    op.drop_constraint('roadmap_cache_learning_path_id_fkey', 'roadmap_cache', type_='foreignkey')
    op.drop_constraint('roadmap_cache_user_id_fkey', 'roadmap_cache', type_='foreignkey')
    
    # Recreate foreign key constraints with CASCADE delete
    op.create_foreign_key('path_modules_path_id_fkey', 'path_modules', 'learning_paths', ['path_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('path_modules_course_id_fkey', 'path_modules', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('courses_path_id_fkey', 'courses', 'learning_paths', ['path_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_progress_module_id_fkey', 'user_progress', 'path_modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_progress_profile_id_fkey', 'user_progress', 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('learning_paths_user_id_fkey', 'learning_paths', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('roadmap_cache_learning_path_id_fkey', 'roadmap_cache', 'learning_paths', ['learning_path_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('roadmap_cache_user_id_fkey', 'roadmap_cache', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Add CASCADE to other relevant foreign keys
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('learning_sessions_user_id_fkey', 'learning_sessions', type_='foreignkey')
    op.drop_constraint('learning_sessions_module_id_fkey', 'learning_sessions', type_='foreignkey')
    op.drop_constraint('learning_sessions_course_id_fkey', 'learning_sessions', type_='foreignkey')
    op.create_foreign_key('learning_sessions_user_id_fkey', 'learning_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('learning_sessions_module_id_fkey', 'learning_sessions', 'path_modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('learning_sessions_course_id_fkey', 'learning_sessions', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    
    # Add CASCADE to activity-related tables
    op.drop_constraint('learning_activities_module_id_fkey', 'learning_activities', type_='foreignkey')
    op.create_foreign_key('learning_activities_module_id_fkey', 'learning_activities', 'path_modules', ['module_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('activity_submissions_user_id_fkey', 'activity_submissions', type_='foreignkey')
    op.drop_constraint('activity_submissions_activity_id_fkey', 'activity_submissions', type_='foreignkey')
    op.create_foreign_key('activity_submissions_user_id_fkey', 'activity_submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('activity_submissions_activity_id_fkey', 'activity_submissions', 'learning_activities', ['activity_id'], ['id'], ondelete='CASCADE')
    
    # Add CASCADE to forum tables
    op.drop_constraint('forum_posts_user_id_fkey', 'forum_posts', type_='foreignkey')
    op.drop_constraint('forum_posts_module_id_fkey', 'forum_posts', type_='foreignkey')
    op.create_foreign_key('forum_posts_user_id_fkey', 'forum_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('forum_posts_module_id_fkey', 'forum_posts', 'path_modules', ['module_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('forum_replies_post_id_fkey', 'forum_replies', type_='foreignkey')
    op.drop_constraint('forum_replies_user_id_fkey', 'forum_replies', type_='foreignkey')
    op.create_foreign_key('forum_replies_post_id_fkey', 'forum_replies', 'forum_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('forum_replies_user_id_fkey', 'forum_replies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Add CASCADE to gamification tables
    op.drop_constraint('user_badges_user_id_fkey', 'user_badges', type_='foreignkey')
    op.create_foreign_key('user_badges_user_id_fkey', 'user_badges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('user_points_user_id_fkey', 'user_points', type_='foreignkey')
    op.create_foreign_key('user_points_user_id_fkey', 'user_points', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Add CASCADE to feedback tables
    op.drop_constraint('module_feedback_user_id_fkey', 'module_feedback', type_='foreignkey')
    op.drop_constraint('module_feedback_module_id_fkey', 'module_feedback', type_='foreignkey')
    op.create_foreign_key('module_feedback_user_id_fkey', 'module_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('module_feedback_module_id_fkey', 'module_feedback', 'path_modules', ['module_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('course_feedback_user_id_fkey', 'course_feedback', type_='foreignkey')
    op.drop_constraint('course_feedback_course_id_fkey', 'course_feedback', type_='foreignkey')
    op.create_foreign_key('course_feedback_user_id_fkey', 'course_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('course_feedback_course_id_fkey', 'course_feedback', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    
    # Add CASCADE to streak table
    op.drop_constraint('user_streaks_user_id_fkey', 'user_streaks', type_='foreignkey')
    op.create_foreign_key('user_streaks_user_id_fkey', 'user_streaks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert back to original foreign keys without CASCADE
    op.drop_constraint('path_modules_path_id_fkey', 'path_modules', type_='foreignkey')
    op.drop_constraint('path_modules_course_id_fkey', 'path_modules', type_='foreignkey')
    op.drop_constraint('courses_path_id_fkey', 'courses', type_='foreignkey')
    op.drop_constraint('user_progress_module_id_fkey', 'user_progress', type_='foreignkey')
    op.drop_constraint('user_progress_profile_id_fkey', 'user_progress', type_='foreignkey')
    op.drop_constraint('learning_paths_user_id_fkey', 'learning_paths', type_='foreignkey')
    op.drop_constraint('roadmap_cache_learning_path_id_fkey', 'roadmap_cache', type_='foreignkey')
    op.drop_constraint('roadmap_cache_user_id_fkey', 'roadmap_cache', type_='foreignkey')
    
    # Recreate original foreign keys
    op.create_foreign_key('path_modules_path_id_fkey', 'path_modules', 'learning_paths', ['path_id'], ['id'])
    op.create_foreign_key('path_modules_course_id_fkey', 'path_modules', 'courses', ['course_id'], ['id'])
    op.create_foreign_key('courses_path_id_fkey', 'courses', 'learning_paths', ['path_id'], ['id'])
    op.create_foreign_key('user_progress_module_id_fkey', 'user_progress', 'path_modules', ['module_id'], ['id'])
    op.create_foreign_key('user_progress_profile_id_fkey', 'user_progress', 'user_profiles', ['profile_id'], ['id'])
    op.create_foreign_key('learning_paths_user_id_fkey', 'learning_paths', 'users', ['user_id'], ['id'])
    op.create_foreign_key('roadmap_cache_learning_path_id_fkey', 'roadmap_cache', 'learning_paths', ['learning_path_id'], ['id'])
    op.create_foreign_key('roadmap_cache_user_id_fkey', 'roadmap_cache', 'users', ['user_id'], ['id'])
    
    # Revert other foreign keys
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'])
    
    # Revert learning sessions
    op.drop_constraint('learning_sessions_user_id_fkey', 'learning_sessions', type_='foreignkey')
    op.drop_constraint('learning_sessions_module_id_fkey', 'learning_sessions', type_='foreignkey')
    op.drop_constraint('learning_sessions_course_id_fkey', 'learning_sessions', type_='foreignkey')
    op.create_foreign_key('learning_sessions_user_id_fkey', 'learning_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('learning_sessions_module_id_fkey', 'learning_sessions', 'path_modules', ['module_id'], ['id'])
    op.create_foreign_key('learning_sessions_course_id_fkey', 'learning_sessions', 'courses', ['course_id'], ['id'])
    
    # Revert activity tables
    op.drop_constraint('learning_activities_module_id_fkey', 'learning_activities', type_='foreignkey')
    op.create_foreign_key('learning_activities_module_id_fkey', 'learning_activities', 'path_modules', ['module_id'], ['id'])
    
    op.drop_constraint('activity_submissions_user_id_fkey', 'activity_submissions', type_='foreignkey')
    op.drop_constraint('activity_submissions_activity_id_fkey', 'activity_submissions', type_='foreignkey')
    op.create_foreign_key('activity_submissions_user_id_fkey', 'activity_submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('activity_submissions_activity_id_fkey', 'activity_submissions', 'learning_activities', ['activity_id'], ['id'])
    
    # Revert forum tables
    op.drop_constraint('forum_posts_user_id_fkey', 'forum_posts', type_='foreignkey')
    op.drop_constraint('forum_posts_module_id_fkey', 'forum_posts', type_='foreignkey')
    op.create_foreign_key('forum_posts_user_id_fkey', 'forum_posts', 'users', ['user_id'], ['id'])
    op.create_foreign_key('forum_posts_module_id_fkey', 'forum_posts', 'path_modules', ['module_id'], ['id'])
    
    op.drop_constraint('forum_replies_post_id_fkey', 'forum_replies', type_='foreignkey')
    op.drop_constraint('forum_replies_user_id_fkey', 'forum_replies', type_='foreignkey')
    op.create_foreign_key('forum_replies_post_id_fkey', 'forum_replies', 'forum_posts', ['post_id'], ['id'])
    op.create_foreign_key('forum_replies_user_id_fkey', 'forum_replies', 'users', ['user_id'], ['id'])
    
    # Revert gamification tables
    op.drop_constraint('user_badges_user_id_fkey', 'user_badges', type_='foreignkey')
    op.create_foreign_key('user_badges_user_id_fkey', 'user_badges', 'users', ['user_id'], ['id'])
    
    op.drop_constraint('user_points_user_id_fkey', 'user_points', type_='foreignkey')
    op.create_foreign_key('user_points_user_id_fkey', 'user_points', 'users', ['user_id'], ['id'])
    
    # Revert feedback tables
    op.drop_constraint('module_feedback_user_id_fkey', 'module_feedback', type_='foreignkey')
    op.drop_constraint('module_feedback_module_id_fkey', 'module_feedback', type_='foreignkey')
    op.create_foreign_key('module_feedback_user_id_fkey', 'module_feedback', 'users', ['user_id'], ['id'])
    op.create_foreign_key('module_feedback_module_id_fkey', 'module_feedback', 'path_modules', ['module_id'], ['id'])
    
    op.drop_constraint('course_feedback_user_id_fkey', 'course_feedback', type_='foreignkey')
    op.drop_constraint('course_feedback_course_id_fkey', 'course_feedback', type_='foreignkey')
    op.create_foreign_key('course_feedback_user_id_fkey', 'course_feedback', 'users', ['user_id'], ['id'])
    op.create_foreign_key('course_feedback_course_id_fkey', 'course_feedback', 'courses', ['course_id'], ['id'])
    
    # Revert streak table
    op.drop_constraint('user_streaks_user_id_fkey', 'user_streaks', type_='foreignkey')
    op.create_foreign_key('user_streaks_user_id_fkey', 'user_streaks', 'users', ['user_id'], ['id'])
    